### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by mostafaznv** [nutgram/nutgram#162]
### Describe the bug

Hi. Thanks for your great package.

I've built a small bot (using self-hosted telegram-bot-api) to compress PDF file. 
It needs to download and upload attached files.
It worked well till recently and suddenly I faced this error:

```
Bad Request: invalid file_id

 #0 /vendor/nutgram/nutgram/src/Telegram/Client.php(269): SergiX44\Nutgram\Nutgram->mapResponse()
 #1 /vendor/nutgram/nutgram/src/Telegram/Endpoints/AvailableMethods.php(482): SergiX44\Nutgram\Nutgram->requestJson()
 #2 /src/Domain/PDF/Actions/CompressPdfAction.php(49): SergiX44\Nutgram\Nutgram->getFile()
```

It seems it can't download file

### Expected behavior

Download attached file

**Comment by Lukasss93** [comment]
Can you show us how you download the file?

**Comment by mostafaznv** [comment]
```
private Nutgram $telegram;


$this->telegram->getFile($compressionRequest->file_id)->file_path;
```

Note: `$compressionRequest->file_id` has value.

**Comment by Lukasss93** [comment]
Are you sure your file_id is valid?
Follow this article for more info: https://nutgram.dev/docs/usage/sending_requests/#downloading-media

PS: we released a new Nutgram version: https://github.com/nutgram/nutgram/releases/tag/3.3.0

**Comment by mostafaznv** [comment]
Yes it is.
I get it using this code:

```php
$document = $bot->update()->getMessage()->document; // or $bot->message()->document
$fileId = $document->file_id

// example: BQACAgQAAxkBAAID0mKw46UVRWSAXGzQouQ48wwXmkcQAALrDQACyceJUbZXXqZ9MWFVKAQ
```

**Comment by mostafaznv** [comment]
I tried to call getUpdates manually with this curl command:

```bash
➜  curl http://localhost:8081/bot<TOKEN>/getUpdates
```

And this is the comparison between command-line data and the one that I got from the package:

CURL: `BQACAgQAAxkBAAID8mKxAs-cs3PKhmudP3zIpr0K3pH1AALrDQACyceJUbZXXqZ9MWFVJAQ`
Package: `BQACAgQAAxkBAAID8mKxAs-cs3PKhmudP3zIpr0K3pH1AALrDQACyceJUbZXXqZ9MWFVKAQ`

Then I tried to call getFile using this curl command:

```bash
➜ curl http://localhost:8081/bot<TOKEN>/getFile\?file_id\=<FILE_ID>
```

I got error with the package's file_id while the curl's file_id worked fine.
I tried these steps with other files too. there were always a difference between package and command-line.

**Comment by Lukasss93** [comment]
I was unable to replicate the problem.
Try using another bot api server

I used this one:
https://registry.hub.docker.com/r/aiogram/telegram-bot-api

**Comment by mostafaznv** [comment]
Problem solved.

My bot api server was a compiled version of telegram's official [source code](https://github.com/tdlib/telegram-bot-api)
Last night I tried to updated it and it updated to 6.0.1 
Tonight I updated it again and with 6.1 (latest version), everything is OK again.

Thank you
