### ISSUE TITLE
How to get service parameter inside command class (Symfony)?

### ISSUE THREAD

**Issue by sherwomeister** [nutgram/nutgram#625]
### Nutgram version

4.x

### PHP version

8.2

### Framework

Symfony

### Describe the bug

Can't autowire a service parameter in command class: ` "Too few arguments to function App\Telegram\Command\StartCommand::__construct(), 0 passed in /vendor/nutgram/nutgram/src/Handlers/Listeners/MessageListeners.php on line 44 and exactly 1 expected"`

### To Reproduce

Create a command class in src/Telegram/Commands with constructor that requires parameter:

```php
public function __construct(
        private $ownerId
    ) {
}
```
Add to services.yaml:
```yaml
App\Telegram\Command\StartCommand:
  arguments:
      $ownerId: 'test'
```

### Additional context

Symfony 6
Using nutgram bundle

**Comment by sherwomeister** [comment]
How to pass entityManager to a command class?

**Comment by Lukasss93** [comment]
To use the container in the "command" class, use the "handle" method, not the "__construct" method.

Example:
```php
class StartCommand extends Command
{
    protected string $command = 'start';
    protected ?string $description = 'Initial bot message';

    public function handle(Nutgram $bot, string $ownerId): void
    {
        // $ownerId is test
    }
}

```

**Comment by sherwomeister** [comment]
> To use the container in the `Command` class, use the `handle` method, not the `__construct` method.
> 
> Example:
> 
> ```
> class StartCommand extends Command
> {
>     protected string $command = 'start';
>     protected ?string $description = 'Initial bot message';
> 
>     public function handle(Nutgram $bot, string $ownerId): void
>     {
>         // $ownerId is test
>     }
> }
> ```

How to access parameters for example in scopes() function?

**Comment by sherwomeister** [comment]
I tried binding, explicitly setting arguments, tried accessing it via ParameterBag, but I just can't get the variable a need neither in constructor nor in handle() function.

**Comment by ant1quariat** [comment]
Commands with arguments that are created via the Command class do not work correctly. In the screenshot below you can see that the response from the command is not returned, but.
![image](https://github.com/user-attachments/assets/e319b6bc-00bc-4ac5-8fd4-01db5673695d)

If you do not specify a parameter when entering the command, an error occurs, which is shown in the second attachment:
```log
SergiX44\Container\Exception\ContainerException: Cannot resolve parameter '$web::SkyGoose\GroupMessageBot\commands\RegisterCommand' in H:\composer\GroupMessageBot\vendor\sergix44\container\src\Exception\ContainerException.php:18
Stack trace:
#0 H:\composer\GroupMessageBot\vendor\sergix44\container\src\Container.php(210): SergiX44\Container\Exception\ContainerException::parameterNotResolvable(Object(ReflectionParameter))
#1 H:\composer\GroupMessageBot\vendor\sergix44\container\src\Container.php(150): SergiX44\Container\Container->getArguments(Array, Array)
#2 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Nutgram.php(357): SergiX44\Container\Container->call(Array, Array)
#3 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Handlers\Handler.php(160): SergiX44\Nutgram\Nutgram->invoke(Array, Array)
#4 [internal function]: SergiX44\Nutgram\Handlers\Handler->__invoke(Object(SergiX44\Nutgram\Nutgram))
#5 H:\composer\GroupMessageBot\vendor\sergix44\container\src\Container.php(152): call_user_func_array(Object(SkyGoose\GroupMessageBot\commands\RegisterCommand), Array)
#6 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Nutgram.php(357): SergiX44\Container\Container->call(Object(SkyGoose\GroupMessageBot\commands\RegisterCommand), Array)
#7 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Middleware\Link.php(37): SergiX44\Nutgram\Nutgram->invoke(Object(SkyGoose\GroupMessageBot\commands\RegisterCommand), Array)
#8 [internal function]: SergiX44\Nutgram\Middleware\Link->__invoke(Object(SergiX44\Nutgram\Nutgram))
#9 H:\composer\GroupMessageBot\vendor\sergix44\container\src\Container.php(152): call_user_func_array(Object(SergiX44\Nutgram\Middleware\Link), Array)
#10 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Nutgram.php(357): SergiX44\Container\Container->call(Object(SergiX44\Nutgram\Middleware\Link), Array)
#11 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Handlers\FireHandlers.php(60): SergiX44\Nutgram\Nutgram->invoke(Object(SergiX44\Nutgram\Middleware\Link))
#12 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Nutgram.php(234): SergiX44\Nutgram\Nutgram->fireHandlers(Array)
#13 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\RunningMode\Polling.php(79): SergiX44\Nutgram\Nutgram->processUpdate(Object(SergiX44\Nutgram\Telegram\Types\Common\Update))
#14 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\RunningMode\Polling.php(51): SergiX44\Nutgram\RunningMode\Polling->fire(Object(SergiX44\Nutgram\Nutgram), Array)
#15 H:\composer\GroupMessageBot\vendor\nutgram\nutgram\src\Nutgram.php(206): SergiX44\Nutgram\RunningMode\Polling->processUpdates(Object(SergiX44\Nutgram\Nutgram))
#16 H:\composer\GroupMessageBot\src\Main.php(47): SergiX44\Nutgram\Nutgram->run()
#17 H:\composer\GroupMessageBot\index.php(11): SkyGoose\GroupMessageBot\Main::main(Array)
#18 {main}
```
