### ISSUE TITLE
[BUG] middleware() method accepts array but passing an array causes an error

### ISSUE THREAD

**Issue by andreich1980** [nutgram/nutgram#783]
### Nutgram version

nutgram/laravel v1.4.3

### PHP version

8.2.19

### Framework

Laravel Framework 11.28.1

### Cache driver

database

### OS

Windows 11

### Dev environment

Laragon

### Describe the bug

Method signature is

```php
public function middleware(string|array|callable|object $callable): self
```

It works if I pass a class (MyMiddleware::class) or an instance of class (new MyMiddleware()).
But if I pass an array (so I could pass a few middlewares), it fails with an error

```
SergiX44\Container\Exception\ContainerException: Invalid callable specified in C:\Laragon\www\target-tamer\vendor\sergix44\container\src\Exception\ContainerException.php:23
Stack trace:
#0 C:\Laragon\www\target-tamer\vendor\sergix44\container\src\Container.php(147): SergiX44\Container\Exception\ContainerException::invalidCallable()
#1 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\Nutgram.php(353): SergiX44\Container\Container->call(Array, Array)
#2 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\Middleware\Link.php(37): SergiX44\Nutgram\Nutgram->invoke(Array, Array)
#3 [internal function]: SergiX44\Nutgram\Middleware\Link->__invoke(Object(SergiX44\Nutgram\Nutgram))
#4 C:\Laragon\www\target-tamer\vendor\sergix44\container\src\Container.php(152): call_user_func_array(Object(SergiX44\Nutgram\Middleware\Link), Array)
#5 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\Nutgram.php(353): SergiX44\Container\Container->call(Object(SergiX44\Nutgram\Middleware\Link), Array)
#6 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\Handlers\FireHandlers.php(60): SergiX44\Nutgram\Nutgram->invoke(Object(SergiX44\Nutgram\Middleware\Link))
#7 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\Nutgram.php(230): SergiX44\Nutgram\Nutgram->fireHandlers(Array)
#8 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\RunningMode\Polling.php(79): SergiX44\Nutgram\Nutgram->processUpdate(Object(SergiX44\Nutgram\Telegram\Types\Common\Update))
#9 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\RunningMode\Polling.php(51): SergiX44\Nutgram\RunningMode\Polling->fire(Object(SergiX44\Nutgram\Nutgram), Array)
#10 C:\Laragon\www\target-tamer\vendor\nutgram\nutgram\src\Nutgram.php(202): SergiX44\Nutgram\RunningMode\Polling->processUpdates(Object(SergiX44\Nutgram\Nutgram))
#11 C:\Laragon\www\target-tamer\vendor\nutgram\laravel\src\Console\RunCommand.php(22): SergiX44\Nutgram\Nutgram->run()
#12 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(36): Nutgram\Laravel\Console\RunCommand->handle(Object(SergiX44\Nutgram\Nutgram))
#13 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Container\Util.php(43): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(95): Illuminate\Container\Util::unwrapIfClosure(Object(Closure))
#15 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Container\BoundMethod.php(35): Illuminate\Container\BoundMethod::callBoundMethod(Object(Illuminate\Foundation\Application), Array, Object(Closure))
#16 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Container\Container.php(690): Illuminate\Container\BoundMethod::call(Object(Illuminate\Foundation\Application), Array, Array, NULL)
#17 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Console\Command.php(213): Illuminate\Container\Container->call(Array)
#18 C:\Laragon\www\target-tamer\vendor\symfony\console\Command\Command.php(279): Illuminate\Console\Command->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#19 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Console\Command.php(182): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Illuminate\Console\OutputStyle))
#20 C:\Laragon\www\target-tamer\vendor\symfony\console\Application.php(1047): Illuminate\Console\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#21 C:\Laragon\www\target-tamer\vendor\symfony\console\Application.php(316): Symfony\Component\Console\Application->doRunCommand(Object(Nutgram\Laravel\Console\RunCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#22 C:\Laragon\www\target-tamer\vendor\symfony\console\Application.php(167): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#23 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Foundation\Console\Kernel.php(197): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#24 C:\Laragon\www\target-tamer\vendor\laravel\framework\src\Illuminate\Foundation\Application.php(1203): Illuminate\Foundation\Console\Kernel->handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#25 C:\Laragon\www\target-tamer\artisan(13): Illuminate\Foundation\Application->handleCommand(Object(Symfony\Component\Console\Input\ArgvInput))
#26 {main}
```

### To Reproduce

```php
// routes/telegram.php

$bot->group(function () use ($bot) {
    $bot->registerCommand(StartCommand::class);
})->middleware([GroupChatCommand::class]);
```

### Expected behavior

It should work fine according to the argument types

### Additional context

Original method implementation

```php
    public function middleware(string|array|callable|object $callable): self
    {
        array_unshift($this->middlewares, $callable);
        return $this;
    }
```

Probably, we should check the argument type here and act accordingly:

```php
    public function middleware(string|array|callable|object $callable): self
    {
        if (is_array($callable)) {
            array_unshift($this->middlewares, ...$callable);
        } else {
            array_unshift($this->middlewares, $callable);
        }
        return $this;
    }
```

Please, let me know if you would like me to create a PR.

**Comment by sergix44** [comment]
Because is not a valid callable, simply as that. It accept an array, but that doesn't mean that you can throw whatever array to it and expect it to should always work, and sadly you cannot define array shapes natively.

```php
$bot->onCommand('start', StartCommand::class)
    ->middleware(LoadUser::class); // yes, if class is invokable

$bot->onCommand('start', StartCommand::class)
    ->middleware([LoadUser::class, 'fetchUser']); // yes, define class method

$bot->onCommand('start', StartCommand::class)
    ->middleware([new LoadUser, 'fetchUser']); // yes, define class method, accepts also instances

$bot->onCommand('start', StartCommand::class)
    ->middleware(LoadUser::class);
    ->middleware(SomethingElse::class); // yes
    
$bot->onCommand('start', StartCommand::class)
    ->middleware(function (...) { ... }); // yes
    
$bot->onCommand('start', StartCommand::class)
    ->middleware([LoadUser::class]); // invalid callable

$bot->onCommand('start', StartCommand::class)
    ->middleware([1,2,3]); // invalid callable

$bot->onCommand('start', StartCommand::class)
    ->middleware(new ZipArchive); // invalid callable
```

**Comment by andreich1980** [comment]
Oh, cool. I thought it should accept an array of middleware class names or instances. 
Thanks for the explanation.
